FROM rabbitmq:4.0.7-management
RUN apt-get update
RUN apt-get install -y curl
RUN curl -L https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.7/rabbitmq_delayed_message_exchange-v4.0.7.ez > $RABBITMQ_HOME/plugins/rabbitmq_delayed_message_exchange-4.0.7.ez
RUN chown rabbitmq:rabbitmq $RABBITMQ_HOME/plugins/rabbitmq_delayed_message_exchange-4.0.7.ez
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange